#!/bin/bash

# Created by Joey Takeda.
# This script takes in a PDF and uses tesseract and convert (through ImageMagick)
# to create an OCR'd version of the PDF. It does so with density of 300.

# NOTE: If it the text from the PDF is what's desired, this process is probably
# still the easiest solution. Use the final PDF created and then use pdftotext to
# extract the text.

#PDF is the input PDF
PDF="$1";
PDF_NAME="${PDF%%.pdf}";
TEMP_DIR_NAME="${PDF_NAME}"_temp;
SEP="==================================";
#Set an empty variable here.
PROCESS_FILES="";
echo $SEP;
if [[ -f $PDF && -n $PDF ]]; then
	echo "Converting" $1;
	echo $SEP;
	echo "Splitting PDF into multiple PNG files.";
	
	# Make temporary directory
	
	mkdir $TEMP_DIR_NAME;
	
	# Now use convert (pkg from imagemagick) to convert PDF to PNG.
	# JT 2017.03.28 edited this to make filename just 't-' to fix output

	convert -density 300 $PDF $TEMP_DIR_NAME/t.png;
	echo $SEP;
	echo "Now taking those split PDFs and OCRing.";
	echo $SEP;
	# For all of the newly created PNGs, create OCR'd version of the PDF
	for i in $TEMP_DIR_NAME/*.png;
	do tesseract $i ${i:-4} pdf;
	done;
	
	#Now combining PDFs
	
	#First get all the file names and plug them into a file
	cd $TEMP_DIR_NAME;
	ls *.png.pdf | sort -t- -n -k2 > listOfFiles.txt;
	
	# Read this file and concatenate these all into one line of text
	while read line; do 
		PROCESS_FILES+=$line" "
	done < listOfFiles.txt;
	
	#Now combine them using pdfunite
	echo $SEP;
	echo "Combining separate PDF files"
	
	# This PDF should be in the same directory as the input PDF
	# and will have the same name with _ocr appended.
	
	pdfunite $PROCESS_FILES ../$PDF_NAME"_ocr.pdf";
	echo $SEP;
	
	# The temp file isn't necessary anymore, but it might be helpful.
	
	echo "Would you like to delete the separate png files? (Y/N)"
	read DELETE_ANSWER
	if [ DELETE_ANSWER=="Y" ]; then
		cd ../;
		echo "Delete temp folder $TEMP_DIR_NAME";
		rm -r $TEMP_DIR_NAME;
	fi
	echo $SEP;
	echo "Process complete!"
else
	echo "Error PDF file needed."
	echo "Sample command: ocrPdf filename.pdf";
		
fi;