name: Build site

on: [push, workflow_dispatch]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Self checkout
        uses: actions/checkout@v5
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Setup node
        uses: actions/setup-node@v4
      - name: NPM install
        run: npm install
      - name: Compile
        run: npm run build
      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v4
        with:
          path: ${{ github.workspace }}/dist
      - name: Deploy
        uses: actions/deploy-pages@v4
