name: Build site

on: [push, workflow_dispatch]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Self checkout
        uses: actions/checkout@v2
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Setup node
        uses: actions/setup-node@v3
      - name: NPM install
        run: npm install
      - name: Compile
        run: cp -r ${{ github.workspace }}/docs ${{ github.workspace}}/public/docs && vite build
      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v2
        with:
          path: ${{ github.workspace }}/dist
      - name: Deploy
        uses: actions/deploy-pages@v2